### PR TITLE
Escape shell vars in HCL output

### LINKED ISSUE #27: Escape shell variables (`${...}`) in text fields so Terraform doesn't try to interpolate them
Hi John!

I do not know if this is a problem with tfk8s or terraform validate but I am trying to convert knative operator from yaml to terraform and I am encountering errors. I believe a variable in a text field is supposed to be converted from ${NAME} to $${NAME} to be valid in terraform?

Using the input below:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  TEST: "${TEST}"
```

```
> cat input.yaml | tfk8s > output.tf && terraform init && terraform validate
```

Gives:

```
╷
│ Error: Invalid reference
│
│   on output.tf line 5, in resource "kubernetes_manifest" "configmap_test":
│    5:       "TEST" = "${TEST}"
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
```

My actual scenario

```
>  curl -L https://github.com/knative/operator/releases/download/v0.25.0/operator.yaml | tfk8s -o output.tf; terraform init && terraform validate
```

 Gives:

```
| Error: Invalid reference
|
|   on main.tf line 155, in resource "kubernetes_manifest" "customresourcedefinition_knativeeventings_operator_knative_dev":
|  155:                           "description" = "The default image reference template to use for all knative images. Takes the form of example-registry.io/custom/path/${NAME}:custom-tag"
|
```

### PR DESCRIPTION
**Pull request by jrhouston**
Closes #27

### CODE REVIEW

File: tfk8s.go [hunk 1]
```diff
@@ -88,6 +88,12 @@ func snakify(s string) string {
 	return strings.ToLower(re.ReplaceAllString(s, "_"))
 }
 
+// escape incidences of ${} with $${} to prevent Terraform trying to interpolate them
+func escapeShellVars(s string) string {
+	r := regexp.MustCompile(`(\${.*?})`)
```
Comment (jrhouston) [inline tfk8s.go:93]: The `.*?` here is to make the regexp not greedy – otherwise it would match `${VAR1} ${VAR2}` as one group.

File: tfk8s.go [hunk 2]
```diff
@@ -88,6 +88,12 @@ func snakify(s string) string {
...
+	return r.ReplaceAllString(s, `$$$1`)
```
Comment (jrhouston) [inline tfk8s.go:94]: There is three `$` because `$1` uses the first group, then we need to escape the `$` we want to put in front of it 😅

**Comment by jrhouston** [comment]
@curtbushko if you want to try this for your use case and make sure it works.

**Comment by jrhouston** [comment]
Just tried the with the manifest mentioned in the issue and it validates successfully.
